import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ur' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'or' | 'as';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: { code: Language; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.system': 'System',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.donate': 'Donate',
    'nav.startSolving': 'Start Solving',
    'nav.settings': 'Settings',
    'nav.language': 'Language',
    
    // Homepage
    'home.badge': 'AI-Powered Reuse Ideas',
    'home.title': 'Fixit Mentor —',
    'home.titleHighlight': 'Smart Ideas for Broken Items',
    'home.subtitle': 'Get creative AI-powered ideas to reuse your broken or waste items instead of throwing them away.',
    'home.getStarted': 'Get Ideas',
    'home.learnMore': 'Learn More',
    'home.problemTitle': 'Why Throw Away?',
    'home.problemDesc': 'Most people throw away broken items without knowing they can be reused creatively. Our AI helps you discover smart ways to give them new life.',
    'home.comparisonTitle': 'Fixit Mentor vs Normal AI',
    'home.normalAI': 'Normal AI',
    'home.fixitAI': 'Fixit Mentor',
    'home.diff1Normal': 'Perfect prompt needed',
    'home.diff1Fixit': 'No prompt needed',
    'home.diff2Normal': 'Generic suggestions',
    'home.diff2Fixit': 'Personalized project ideas',
    'home.diff3Normal': 'No budget consideration',
    'home.diff3Fixit': 'Budget-friendly solutions',
    'home.diff4Normal': 'Complex setup required',
    'home.diff4Fixit': 'Simple 3-step process',
    'home.diff5Normal': 'Limited material guidance',
    'home.diff5Fixit': 'Complete materials & steps',
    'home.howItWorksTitle': 'How It Works',
    'home.howItWorksDesc': 'Get smart reuse ideas in 3 simple steps',
    'home.step1Title': 'Identify',
    'home.step1Desc': 'Tell us about your broken item',
    'home.step2Title': 'Analyse',
    'home.step2Desc': 'We check reuse possibilities',
    'home.step3Title': 'Evaluate',
    'home.step3Desc': 'Get creative project ideas',
    'home.exampleTitle': 'What Makes Fixit Mentor Different?',
    'home.exampleBadge': 'Real Example',
    'home.exampleQuestion': 'I have a broken laptop — what can I do with it?',
    'home.example1Title': '1. Identify the Item',
    'home.example1Desc': 'Broken laptop, non-functional screen',
    'home.example2Title': '2. Analyse Condition',
    'home.example2Desc': 'Parts working: keyboard, hard drive, motherboard',
    'home.example3Title': '3. Evaluate Options',
    'home.example3Desc': 'Make a digital photo frame, media center, or donate parts',
    'home.example4Title': '4. Project Ideas',
    'home.example4Desc': 'DIY home server, retro gaming console, learn coding platform',
    'home.tryIt': 'Try It Yourself',
    'home.footerDesc': 'An AI-powered platform to get creative ideas for reusing broken items.',
    'home.quickLinks': 'Quick Links',
    'home.contactTitle': 'Contact',
    'home.getInTouch': 'Get in Touch',
    'home.copyright': '© 2025 Fixit Mentor. All rights reserved.',
    
    // System Page
    'system.title': 'Get Smart Reuse Ideas',
    'system.subtitle': 'Tell us about your broken or waste item and get creative AI-powered suggestions',
    'system.wasteItemLabel': 'Broken/Waste Item',
    'system.wasteItemPlaceholder': 'Describe your broken or waste item... (e.g., "broken laptop", "old plastic bottles", "torn jeans")',
    'system.budgetLabel': 'Budget (₹)',
    'system.budgetPlaceholder': 'How much can you spend?',
    'system.otherInfoLabel': 'Additional Info (Optional)',
    'system.otherInfoPlaceholder': 'Any other details... (e.g., "I have basic tools", "prefer eco-friendly ideas")',
    'system.generateButton': 'Generate Smart Reuse Plan',
    'system.generating': 'Generating Ideas...',
    'system.errorWasteItem': 'Please describe your broken/waste item',
    'system.errorBudget': 'Please enter a valid budget',
    
    // Response Page
    'response.backButton': 'Back to System',
    'response.newPlan': 'Generate New Plan',
    'response.noResponseTitle': 'No Response Generated Yet',
    'response.noResponseDesc': 'The response is empty. Please try again with different inputs or check your backend configuration.',
    'response.errorDesc': 'There was an issue generating your plan. This could be due to API configuration or connectivity issues.',
    'response.yourInputs': 'Your inputs:',
    'response.wasteItem': 'Broken Item:',
    'response.budget': 'Budget:',
    'response.otherInfo': 'Other Info:',
    'response.tryAgain': 'Try Again',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.system': 'सिस्टम',
    'nav.about': 'के बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.donate': 'दान करें',
    'nav.startSolving': 'शुरू करें',
    'nav.settings': 'सेटिंग्स',
    'nav.language': 'भाषा',
    
    // Homepage
    'home.badge': 'एआई-संचालित पुनः उपयोग विचार',
    'home.title': 'फिक्सिट मेंटर —',
    'home.titleHighlight': 'टूटी चीजों के लिए स्मार्ट आइडियाज़',
    'home.subtitle': 'अपनी टूटी या बेकार चीजों को फेंकने के बजाय उन्हें पुनः उपयोग करने के लिए रचनात्मक एआई-संचालित विचार प्राप्त करें।',
    'home.getStarted': 'आइडियाज़ पाएं',
    'home.learnMore': 'और जानें',
    'home.problemTitle': 'फेंकना क्यों?',
    'home.problemDesc': 'ज्यादातर लोग टूटी चीजों को बिना जाने फेंक देते हैं कि उन्हें रचनात्मक तरीके से पुनः उपयोग किया जा सकता है। हमारा एआई आपको उन्हें नया जीवन देने के स्मार्ट तरीके खोजने में मदद करता है।',
    'home.comparisonTitle': 'फिक्सिट मेंटर बनाम सामान्य एआई',
    'home.normalAI': 'सामान्य एआई',
    'home.fixitAI': 'फिक्सिट मेंटर',
    'home.diff1Normal': 'परफेक्ट प्रॉम्प्ट की जरूरत',
    'home.diff1Fixit': 'प्रॉम्प्ट की जरूरत नहीं',
    'home.diff2Normal': 'सामान्य सुझाव',
    'home.diff2Fixit': 'व्यक्तिगत परियोजना विचार',
    'home.diff3Normal': 'बजट विचार नहीं',
    'home.diff3Fixit': 'बजट-अनुकूल समाधान',
    'home.diff4Normal': 'जटिल सेटअप आवश्यक',
    'home.diff4Fixit': 'सरल 3-चरण प्रक्रिया',
    'home.diff5Normal': 'सीमित सामग्री मार्गदर्शन',
    'home.diff5Fixit': 'पूर्ण सामग्री और चरण',
    'home.howItWorksTitle': 'यह कैसे काम करता है',
    'home.howItWorksDesc': '3 सरल चरणों में स्मार्ट पुनः उपयोग विचार प्राप्त करें',
    'home.step1Title': 'पहचानें',
    'home.step1Desc': 'हमें अपनी टूटी चीज के बारे में बताएं',
    'home.step2Title': 'विश्लेषण करें',
    'home.step2Desc': 'हम पुनः उपयोग की संभावनाओं की जांच करते हैं',
    'home.step3Title': 'मूल्यांकन करें',
    'home.step3Desc': 'रचनात्मक परियोजना विचार प्राप्त करें',
    'home.exampleTitle': 'फिक्सिट मेंटर को क्या अलग बनाता है?',
    'home.exampleBadge': 'वास्तविक उदाहरण',
    'home.exampleQuestion': 'मेरे पास एक टूटा हुआ लैपटॉप है — मैं इसके साथ क्या कर सकता हूं?',
    'home.example1Title': '1. आइटम की पहचान करें',
    'home.example1Desc': 'टूटा हुआ लैपटॉप, गैर-कार्यात्मक स्क्रीन',
    'home.example2Title': '2. स्थिति का विश्लेषण करें',
    'home.example2Desc': 'काम कर रहे भाग: कीबोर्ड, हार्ड ड्राइव, मदरबोर्ड',
    'home.example3Title': '3. विकल्पों का मूल्यांकन करें',
    'home.example3Desc': 'डिजिटल फोटो फ्रेम, मीडिया सेंटर बनाएं या भागों को दान करें',
    'home.example4Title': '4. परियोजना विचार',
    'home.example4Desc': 'DIY होम सर्वर, रेट्रो गेमिंग कंसोल, कोडिंग सीखने का प्लेटफॉर्म',
    'home.tryIt': 'खुद आजमाएं',
    'home.footerDesc': 'टूटी चीजों को पुनः उपयोग करने के रचनात्मक विचार प्राप्त करने के लिए एक एआई-संचालित प्लेटफॉर्म।',
    'home.quickLinks': 'त्वरित लिंक',
    'home.contactTitle': 'संपर्क',
    'home.getInTouch': 'संपर्क में रहें',
    'home.copyright': '© 2025 फिक्सिट मेंटर। सर्वाधिकार सुरक्षित।',
    
    // System Page
    'system.title': 'स्मार्ट पुनः उपयोग विचार प्राप्त करें',
    'system.subtitle': 'हमें अपनी टूटी या बेकार चीज के बारे में बताएं और रचनात्मक एआई-संचालित सुझाव प्राप्त करें',
    'system.wasteItemLabel': 'टूटी/बेकार चीज',
    'system.wasteItemPlaceholder': 'अपनी टूटी या बेकार चीज का वर्णन करें... (जैसे, "टूटा लैपटॉप", "पुरानी प्लास्टिक बोतलें", "फटी जींस")',
    'system.budgetLabel': 'बजट (₹)',
    'system.budgetPlaceholder': 'आप कितना खर्च कर सकते हैं?',
    'system.otherInfoLabel': 'अतिरिक्त जानकारी (वैकल्पिक)',
    'system.otherInfoPlaceholder': 'कोई अन्य विवरण... (जैसे, "मेरे पास बुनियादी उपकरण हैं", "पर्यावरण के अनुकूल विचार पसंद करते हैं")',
    'system.generateButton': 'स्मार्ट पुनः उपयोग योजना बनाएं',
    'system.generating': 'विचार उत्पन्न हो रहे हैं...',
    'system.errorWasteItem': 'कृपया अपनी टूटी/बेकार चीज का वर्णन करें',
    'system.errorBudget': 'कृपया एक मान्य बजट दर्ज करें',
    
    // Response Page
    'response.backButton': 'सिस्टम पर वापस जाएं',
    'response.newPlan': 'नई योजना बनाएं',
    'response.noResponseTitle': 'अभी तक कोई प्रतिक्रिया उत्पन्न नहीं हुई',
    'response.noResponseDesc': 'प्रतिक्रिया खाली है। कृपया विभिन्न इनपुट के साथ पुनः प्रयास करें या अपने बैकएंड कॉन्फ़िगरेशन की जांच करें।',
    'response.errorDesc': 'आपकी योजना उत्पन्न करने में समस्या थी। यह एपीआई कॉन्फ़िगरेशन या कनेक्टिविटी समस्याओं के कारण हो सकता है।',
    'response.yourInputs': 'आपके इनपुट:',
    'response.wasteItem': 'टूटी चीज:',
    'response.budget': 'बजट:',
    'response.otherInfo': 'अन्य जानकारी:',
    'response.tryAgain': 'पुनः प्रयास करें',
  },
  ur: {
    'nav.home': 'گھر',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.system': 'سسٹم',
    'nav.about': 'کے بارے میں',
    'nav.contact': 'رابطہ کریں',
    'nav.donate': 'عطیہ دیں',
    'nav.startSolving': 'شروع کریں',
    'nav.settings': 'ترتیبات',
    'nav.language': 'زبان',
    'home.badge': 'اے آئی سے چلنے والے دوبارہ استعمال کے خیالات',
    'home.title': 'فکسٹ منٹر —',
    'home.titleHighlight': 'ٹوٹی چیزوں کے لیے سمارٹ آئیڈیاز',
    'home.subtitle': 'اپنی ٹوٹی یا فضول چیزوں کو پھینکنے کے بجائے انہیں دوبارہ استعمال کرنے کے لیے تخلیقی اے آئی سے چلنے والے خیالات حاصل کریں۔',
    'home.getStarted': 'آئیڈیاز حاصل کریں',
    'home.learnMore': 'مزید جانیں',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.system': 'সিস্টেম',
    'nav.about': 'সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.donate': 'দান করুন',
    'nav.startSolving': 'শুরু করুন',
    'nav.settings': 'সেটিংস',
    'nav.language': 'ভাষা',
    'home.badge': 'এআই-চালিত পুনঃব্যবহার ধারণা',
    'home.title': 'ফিক্সিট মেন্টর —',
    'home.titleHighlight': 'ভাঙা জিনিসের জন্য স্মার্ট আইডিয়া',
    'home.subtitle': 'আপনার ভাঙা বা বর্জ্য জিনিসগুলি ফেলে না দিয়ে পুনরায় ব্যবহার করার জন্য সৃজনশীল এআই-চালিত ধারণা পান।',
    'home.getStarted': 'আইডিয়া পান',
    'home.learnMore': 'আরও জানুন',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.system': 'சிஸ்டம்',
    'nav.about': 'பற்றி',
    'nav.contact': 'தொடர்பு',
    'nav.donate': 'நன்கொடை',
    'nav.startSolving': 'தொடங்கு',
    'nav.settings': 'அமைப்புகள்',
    'nav.language': 'மொழி',
    'home.badge': 'AI-இயங்கும் மறுபயன்பாட்டு யோசனைகள்',
    'home.title': 'ஃபிக்ஸிட் மெண்டர் —',
    'home.titleHighlight': 'உடைந்த பொருட்களுக்கான ஸ்மார்ட் ஐடியாக்கள்',
    'home.subtitle': 'உங்கள் உடைந்த அல்லது கழிவு பொருட்களை தூக்கி எறியாமல் மீண்டும் பயன்படுத்த ஆக்கப்பூர்வமான AI-இயங்கும் யோசனைகளைப் பெறுங்கள்.',
    'home.getStarted': 'யோசனைகளைப் பெறுங்கள்',
    'home.learnMore': 'மேலும் அறிக',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.system': 'సిస్టమ్',
    'nav.about': 'గురించి',
    'nav.contact': 'సంప్రదించండి',
    'nav.donate': 'దానం చేయండి',
    'nav.startSolving': 'ప్రారంభించండి',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.language': 'భాష',
    'home.badge': 'AI-శక్తితో పునర్వినియోగ ఆలోచనలు',
    'home.title': 'ఫిక్సిట్ మెంటర్ —',
    'home.titleHighlight': 'విరిగిన వస్తువులకు స్మార్ట్ ఐడియాలు',
    'home.subtitle': 'మీ విరిగిన లేదా వ్యర్థ వస్తువులను విసిరేయకుండా తిరిగి ఉపయోగించడానికి సృజనాత్మక AI-శక్తితో ఆలోచనలను పొందండి.',
    'home.getStarted': 'ఆలోచనలు పొందండి',
    'home.learnMore': 'మరింత తెలుసుకోండి',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.system': 'सिस्टीम',
    'nav.about': 'बद्दल',
    'nav.contact': 'संपर्क',
    'nav.donate': 'दान करा',
    'nav.startSolving': 'सुरू करा',
    'nav.settings': 'सेटिंग्ज',
    'nav.language': 'भाषा',
    'home.badge': 'AI-चालित पुन्हा वापर कल्पना',
    'home.title': 'फिक्सिट मेंटर —',
    'home.titleHighlight': 'तुटलेल्या वस्तूंसाठी स्मार्ट आयडिया',
    'home.subtitle': 'तुमच्या तुटलेल्या किंवा कचऱ्याच्या वस्तू फेकण्याऐवजी त्यांचा पुन्हा वापर करण्यासाठी सर्जनशील AI-चालित कल्पना मिळवा.',
    'home.getStarted': 'कल्पना मिळवा',
    'home.learnMore': 'अधिक जाणून घ्या',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.system': 'સિસ્ટમ',
    'nav.about': 'વિશે',
    'nav.contact': 'સંપર્ક',
    'nav.donate': 'દાન કરો',
    'nav.startSolving': 'શરૂ કરો',
    'nav.settings': 'સેટિંગ્સ',
    'nav.language': 'ભાષા',
    'home.badge': 'AI-સંચાલિત પુનઃઉપયોગ વિચારો',
    'home.title': 'ફિક્સિટ મેંટર —',
    'home.titleHighlight': 'તૂટેલી વસ્તુઓ માટે સ્માર્ટ આઇડિયા',
    'home.subtitle': 'તમારી તૂટેલી અથવા કચરાની વસ્તુઓને ફેંકવાને બદલે તેનો ફરીથી ઉપયોગ કરવા માટે સર્જનાત્મક AI-સંચાલિત વિચારો મેળવો.',
    'home.getStarted': 'આઇડિયા મેળવો',
    'home.learnMore': 'વધુ જાણો',
  },
  kn: {
    'nav.home': 'ಹೋಮ್',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.system': 'ಸಿಸ್ಟಮ್',
    'nav.about': 'ಬಗ್ಗೆ',
    'nav.contact': 'ಸಂಪರ್ಕ',
    'nav.donate': 'ದಾನ ಮಾಡಿ',
    'nav.startSolving': 'ಪ್ರಾರಂಭಿಸಿ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.language': 'ಭಾಷೆ',
    'home.badge': 'AI-ಚಾಲಿತ ಮರುಬಳಕೆ ಆಲೋಚನೆಗಳು',
    'home.title': 'ಫಿಕ್ಸಿಟ್ ಮೆಂಟರ್ —',
    'home.titleHighlight': 'ಮುರಿದ ವಸ್ತುಗಳಿಗೆ ಸ್ಮಾರ್ಟ್ ಐಡಿಯಾಗಳು',
    'home.subtitle': 'ನಿಮ್ಮ ಮುರಿದ ಅಥವಾ ತ್ಯಾಜ್ಯ ವಸ್ತುಗಳನ್ನು ಎಸೆಯುವ ಬದಲು ಮರುಬಳಕೆ ಮಾಡಲು ಸೃಜನಶೀಲ AI-ಚಾಲಿತ ಆಲೋಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'home.getStarted': 'ಆಲೋಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ',
    'home.learnMore': 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.dashboard': 'ഡാഷ്ബോർഡ്',
    'nav.system': 'സിസ്റ്റം',
    'nav.about': 'കുറിച്ച്',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.donate': 'സംഭാവന ചെയ്യുക',
    'nav.startSolving': 'ആരംഭിക്കുക',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.language': 'ഭാഷ',
    'home.badge': 'AI-പവർഡ് പുനരുപയോഗ ആശയങ്ങൾ',
    'home.title': 'ഫിക്സിറ്റ് മെന്റർ —',
    'home.titleHighlight': 'തകർന്ന വസ്തുക്കൾക്കുള്ള സ്മാർട്ട് ആശയങ്ങൾ',
    'home.subtitle': 'നിങ്ങളുടെ തകർന്ന അല്ലെങ്കിൽ മാലിന്യ വസ്തുക്കൾ വലിച്ചെറിയുന്നതിനുപകരം പുനരുപയോഗിക്കാൻ സൃഷ്ടിപരമായ AI-പവർഡ് ആശയങ്ങൾ നേടുക.',
    'home.getStarted': 'ആശയങ്ങൾ നേടുക',
    'home.learnMore': 'കൂടുതൽ അറിയുക',
  },
  pa: {
    'nav.home': 'ਹੋਮ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.system': 'ਸਿਸਟਮ',
    'nav.about': 'ਬਾਰੇ',
    'nav.contact': 'ਸੰਪਰਕ ਕਰੋ',
    'nav.donate': 'ਦਾਨ ਕਰੋ',
    'nav.startSolving': 'ਸ਼ੁਰੂ ਕਰੋ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'nav.language': 'ਭਾਸ਼ਾ',
    'home.badge': 'AI-ਸੰਚਾਲਿਤ ਮੁੜ ਵਰਤੋਂ ਵਿਚਾਰ',
    'home.title': 'ਫਿਕਸਿਟ ਮੈਂਟਰ —',
    'home.titleHighlight': 'ਟੁੱਟੀਆਂ ਚੀਜ਼ਾਂ ਲਈ ਸਮਾਰਟ ਆਈਡੀਆ',
    'home.subtitle': 'ਆਪਣੀਆਂ ਟੁੱਟੀਆਂ ਜਾਂ ਕੂੜੇ ਦੀਆਂ ਚੀਜ਼ਾਂ ਨੂੰ ਸੁੱਟਣ ਦੀ ਬਜਾਏ ਮੁੜ ਵਰਤੋਂ ਕਰਨ ਲਈ ਰਚਨਾਤਮਕ AI-ਸੰਚਾਲਿਤ ਵਿਚਾਰ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'home.getStarted': 'ਆਈਡੀਆ ਪ੍ਰਾਪਤ ਕਰੋ',
    'home.learnMore': 'ਹੋਰ ਜਾਣੋ',
  },
  or: {
    'nav.home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    'nav.dashboard': 'ଡାସବୋର୍ଡ',
    'nav.system': 'ସିଷ୍ଟମ',
    'nav.about': 'ବିଷୟରେ',
    'nav.contact': 'ଯୋଗାଯୋଗ',
    'nav.donate': 'ଦାନ କରନ୍ତୁ',
    'nav.startSolving': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'nav.settings': 'ସେଟିଂସ',
    'nav.language': 'ଭାଷା',
    'home.badge': 'AI-ଚାଳିତ ପୁନଃବ୍ୟବହାର ଧାରଣା',
    'home.title': 'ଫିକ୍ସିଟ ମେଣ୍ଟର —',
    'home.titleHighlight': 'ଭଙ୍ଗା ଜିନିଷ ପାଇଁ ସ୍ମାର୍ଟ ଆଇଡିଆ',
    'home.subtitle': 'ଆପଣଙ୍କର ଭଙ୍ଗା କିମ୍ବା ବର୍ଜ୍ୟ ଜିନିଷଗୁଡ଼ିକୁ ଫୋପାଡି ନ ଦେଇ ପୁନଃବ୍ୟବହାର କରିବା ପାଇଁ ସୃଜନଶୀଳ AI-ଚାଳିତ ଧାରଣା ପାଆନ୍ତୁ।',
    'home.getStarted': 'ଆଇଡିଆ ପାଆନ୍ତୁ',
    'home.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
  },
  as: {
    'nav.home': 'মূল পৃষ্ঠা',
    'nav.dashboard': 'ডেশবৰ্ড',
    'nav.system': 'চিষ্টেম',
    'nav.about': 'বিষয়ে',
    'nav.contact': 'যোগাযোগ',
    'nav.donate': 'দান কৰক',
    'nav.startSolving': 'আৰম্ভ কৰক',
    'nav.settings': 'ছেটিংছ',
    'nav.language': 'ভাষা',
    'home.badge': 'AI-চালিত পুনৰ ব্যৱহাৰ ধাৰণা',
    'home.title': 'ফিক্সিট মেণ্টৰ —',
    'home.titleHighlight': 'ভঙা বস্তুৰ বাবে স্মাৰ্ট আইডিয়া',
    'home.subtitle': 'আপোনাৰ ভঙা বা আৱৰ্জনা বস্তু পেলাই নিদি পুনৰ ব্যৱহাৰ কৰিবলৈ সৃজনশীল AI-চালিত ধাৰণা লাভ কৰক।',
    'home.getStarted': 'আইডিয়া লাভ কৰক',
    'home.learnMore': 'অধিক জানক',
  },
};
