import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ur' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'or' | 'as';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: { code: Language; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.system': 'System',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.donate': 'Donate',
    'nav.startSolving': 'Start Solving',
    'nav.settings': 'Settings',
    'nav.language': 'Language',
    
    // Homepage
    'home.badge': 'AI-Powered Reuse Ideas',
    'home.title': 'Fixit Mentor —',
    'home.titleHighlight': 'Smart Ideas for Broken Items',
    'home.subtitle': 'Get creative AI-powered ideas to reuse your broken or waste items instead of throwing them away.',
    'home.getStarted': 'Get Ideas',
    'home.learnMore': 'Learn More',
    'home.problemTitle': 'Why Throw Away?',
    'home.problemDesc': 'Most people throw away broken items without knowing they can be reused creatively. Our AI helps you discover smart ways to give them new life.',
    'home.comparisonTitle': 'Fixit Mentor vs Normal AI',
    'home.normalAI': 'Normal AI',
    'home.fixitAI': 'Fixit Mentor',
    'home.diff1Normal': 'Perfect prompt needed',
    'home.diff1Fixit': 'No prompt needed',
    'home.diff2Normal': 'Generic suggestions',
    'home.diff2Fixit': 'Personalized project ideas',
    'home.diff3Normal': 'No budget consideration',
    'home.diff3Fixit': 'Budget-friendly solutions',
    'home.diff4Normal': 'Complex setup required',
    'home.diff4Fixit': 'Simple 3-step process',
    'home.diff5Normal': 'Limited material guidance',
    'home.diff5Fixit': 'Complete materials & steps',
    'home.howItWorksTitle': 'How It Works',
    'home.howItWorksDesc': 'Get smart reuse ideas in 3 simple steps',
    'home.step1Title': 'Identify',
    'home.step1Desc': 'Tell us about your broken item',
    'home.step2Title': 'Analyse',
    'home.step2Desc': 'We check reuse possibilities',
    'home.step3Title': 'Evaluate',
    'home.step3Desc': 'Get creative project ideas',
    'home.exampleTitle': 'What Makes Fixit Mentor Different?',
    'home.exampleBadge': 'Real Example',
    'home.exampleQuestion': 'I have a broken laptop — what can I do with it?',
    'home.example1Title': '1. Identify the Item',
    'home.example1Desc': 'Broken laptop, non-functional screen',
    'home.example2Title': '2. Analyse Condition',
    'home.example2Desc': 'Parts working: keyboard, hard drive, motherboard',
    'home.example3Title': '3. Evaluate Options',
    'home.example3Desc': 'Make a digital photo frame, media center, or donate parts',
    'home.example4Title': '4. Project Ideas',
    'home.example4Desc': 'DIY home server, retro gaming console, learn coding platform',
    'home.tryIt': 'Try It Yourself',
    'home.footerDesc': 'An AI-powered platform to get creative ideas for reusing broken items.',
    'home.quickLinks': 'Quick Links',
    'home.contactTitle': 'Contact',
    'home.getInTouch': 'Get in Touch',
    'home.copyright': '© 2025 Fixit Mentor. All rights reserved.',
    
    // System Page
    'system.title': 'Get Smart Reuse Ideas',
    'system.subtitle': 'Tell us about your broken or waste item and get creative AI-powered suggestions',
    'system.wasteItemLabel': 'Broken/Waste Item',
    'system.wasteItemPlaceholder': 'Describe your broken or waste item... (e.g., "broken laptop", "old plastic bottles", "torn jeans")',
    'system.budgetLabel': 'Budget (₹)',
    'system.budgetPlaceholder': 'How much can you spend?',
    'system.otherInfoLabel': 'Additional Info (Optional)',
    'system.otherInfoPlaceholder': 'Any other details... (e.g., "I have basic tools", "prefer eco-friendly ideas")',
    'system.generateButton': 'Generate Smart Reuse Plan',
    'system.generating': 'Generating Ideas...',
    'system.errorWasteItem': 'Please describe your broken/waste item',
    'system.errorBudget': 'Please enter a valid budget',
    
    // Response Page
    'response.backButton': 'Back to System',
    'response.newPlan': 'Generate New Plan',
    'response.noResponseTitle': 'No Response Generated Yet',
    'response.noResponseDesc': 'The response is empty. Please try again with different inputs or check your backend configuration.',
    'response.errorDesc': 'There was an issue generating your plan. This could be due to API configuration or connectivity issues.',
    'response.yourInputs': 'Your inputs:',
    'response.wasteItem': 'Broken Item:',
    'response.budget': 'Budget:',
    'response.otherInfo': 'Other Info:',
    'response.tryAgain': 'Try Again',
    // Response Navigation
    'response.nav.overview': 'Overview',
    'response.nav.idea': 'Project',
    'response.nav.materials': 'Materials',
    'response.nav.steps': 'Steps',
    'response.nav.budget': 'Budget',
    'response.nav.alternate': 'Alternate',
    'response.nav.safety': 'Safety',
    
    // Thank You Page
    'cashOnlyTitle': 'We Only Accept Cash Right Now',
    'selectedAmount': 'Selected Amount',
    'thankYouTitle': 'Thank You for Your Support!',
    'thankYouMessage1': 'Your generous heart and willingness to contribute means the world to us. Every donation, no matter the size, helps us continue our mission of building a more sustainable future through innovative AI solutions.',
    'thankYouMessage2': 'By supporting Fixit Mentor, you are helping countless people discover creative ways to reuse broken items, reduce waste, and contribute to environmental conservation. Your kindness creates a ripple effect that touches lives across communities.',
    'thankYouMessage3': 'We are deeply grateful for your consideration and support. Together, we can make a real difference in how people think about waste and sustainability. Thank you for being part of our journey towards a greener planet.',
    'contactForDonation': 'To complete your cash donation, please contact us at:',
    'backToHome': 'Back to Home',
    
    // Dashboard Page
    'dashboard.title': 'Problem',
    'dashboard.titleHighlight': 'Dashboard',
    'dashboard.subtitle': 'Select a category or search for your specific problem to start the structured thinking process',
    'dashboard.searchPlaceholder': 'Search your problem... (e.g., \'laptop won\'t turn on\', \'need study schedule\')',
    'dashboard.categoriesTitle': 'Common Problem Categories',
    'dashboard.category1Title': 'Electronic Waste',
    'dashboard.category1Desc': 'Broken devices, repair or replace decisions',
    'dashboard.category2Title': 'School Problems',
    'dashboard.category2Desc': 'Study planning, project management, time optimization',
    'dashboard.category3Title': 'Climate / Environment',
    'dashboard.category3Desc': 'Sustainability choices, eco-friendly solutions',
    'dashboard.category4Title': 'Personal Issues',
    'dashboard.category4Desc': 'Life decisions, relationships, health choices',
    'dashboard.category5Title': 'Creative Build Ideas',
    'dashboard.category5Desc': 'DIY projects, innovation, maker problems',
    'dashboard.quickStartTitle': 'Quick Start Examples',
    'dashboard.example1': 'My laptop screen is cracked - should I repair or replace?',
    'dashboard.example2': 'I need to organize my study schedule for 5 subjects',
    'dashboard.example3': 'How can I reduce my carbon footprint on a budget?',
    'dashboard.example4': 'I want to build a solar-powered phone charger',
    'dashboard.startSolving': 'Start solving',
    'dashboard.goToSystem': 'Go to Main System',
    
    // About Page
    'about.title': 'About',
    'about.titleHighlight': 'Fixit Mentor',
    'about.subtitle': 'Understanding the difference between unstructured and structured AI',
    'about.whyNotJustAITitle': 'Why This System is NOT Just AI',
    'about.whyNotJustAIDesc': 'Traditional AI systems give you fast answers, but they lack the structured thinking process that humans naturally use when solving complex problems. Fixit Mentor is different—it\'s a framework that guides you through each critical step of problem-solving, ensuring you consider all angles before making a decision.',
    'about.unstructuredAI': 'Unstructured AI',
    'about.structuredAI': 'Structured AI (Fixit Mentor)',
    'about.unstructured1': 'Single answer without context',
    'about.unstructured2': 'No breakdown of thinking steps',
    'about.unstructured3': 'Doesn\'t consider your constraints',
    'about.unstructured4': 'No comparison of alternatives',
    'about.unstructured5': 'Can\'t adapt to your resources',
    'about.structured1': 'Guided 6-step workflow',
    'about.structured2': 'Clear breakdown of each phase',
    'about.structured3': 'Considers your constraints upfront',
    'about.structured4': 'Compares multiple solution paths',
    'about.structured5': 'Adapts to your specific resources',
    'about.whyPreferTitle': 'Why Students & Innovators Prefer Structured Thinking',
    'about.reason1Title': 'Structured Over Random',
    'about.reason1Desc': 'Our system forces you to think systematically, not just react to the first answer.',
    'about.reason2Title': 'Learn The Process',
    'about.reason2Desc': 'You don\'t just get answers—you learn how to solve similar problems in the future.',
    'about.reason3Title': 'Human-Like Reasoning',
    'about.reason3Desc': 'Mimics how successful problem-solvers think: identify, analyze, evaluate, plan.',
    'about.reason4Title': 'Better Decisions',
    'about.reason4Desc': 'By comparing multiple solutions and their impacts, you make informed choices.',
    'about.howItHelpsTitle': 'How Fixit Mentor Helps You',
    'about.forStudents': 'For Students:',
    'about.forStudentsDesc': 'Learn to approach assignments, projects, and life decisions with a clear, replicable method. This isn\'t just about solving one problem—it\'s about building a mental framework you\'ll use forever.',
    'about.forInnovators': 'For Innovators:',
    'about.forInnovatorsDesc': 'Turn vague ideas into actionable plans. Whether you\'re building a product, starting a project, or solving a technical challenge, the 6-step system ensures nothing is overlooked.',
    'about.forEveryone': 'For Everyone:',
    'about.forEveryoneDesc': 'Make better decisions by seeing the full picture—resources, constraints, alternatives, and impacts—before committing to a solution.',
    
    // Contact Page
    'contact.title': 'Get in',
    'contact.titleHighlight': 'Touch',
    'contact.subtitle': 'Have questions about Fixit Mentor? Want to share feedback? We\'d love to hear from you.',
    'contact.emailTitle': 'Email Us',
    'contact.emailDesc': 'For general inquiries and support',
    'contact.feedbackTitle': 'Feedback',
    'contact.feedbackDesc': 'We\'re constantly improving Fixit Mentor based on user feedback. Share your thoughts and help us make it better for students and innovators everywhere.',
    'contact.whyContactTitle': 'Why Contact Us?',
    'contact.whyContact1': 'Report a bug or technical issue',
    'contact.whyContact2': 'Suggest new features or improvements',
    'contact.whyContact3': 'Partnership or collaboration opportunities',
    'contact.whyContact4': 'Media inquiries',
    'contact.formTitle': 'Send us a Message',
    'contact.nameLabel': 'Your Name',
    'contact.namePlaceholder': 'John Doe',
    'contact.emailLabel': 'Email Address',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.messageLabel': 'Message',
    'contact.messagePlaceholder': 'Tell us what\'s on your mind...',
    'contact.sendButton': 'Send Message',
    'contact.successMessage': 'Message sent! We\'ll get back to you soon.',
    
    // Donate Page
    'donate.badge': 'Support Our Mission',
    'donate.title': 'Help Us Build a',
    'donate.titleHighlight': 'Greener Future',
    'donate.subtitle': 'Your contribution helps us develop better AI tools for sustainable living and environmental conservation.',
    'donate.impact1Title': 'Reduce Waste',
    'donate.impact1Desc': 'Every donation helps us improve our AI models to suggest better recycling solutions.',
    'donate.impact2Title': 'Save Environment',
    'donate.impact2Desc': 'Support sustainable technology that makes eco-friendly choices accessible to everyone.',
    'donate.impact3Title': 'Empower Communities',
    'donate.impact3Desc': 'Help us reach more people with free access to smart recycling solutions.',
    'donate.mainTitle': 'Make a Difference Today',
    'donate.mainDesc': 'Your generous donation will help us continue developing innovative AI solutions for waste reduction and environmental sustainability. Every contribution, big or small, makes a real impact.',
    'donate.donateNow': 'Donate Now',
    'donate.securePayment': 'Secure payment processing. Your contribution is tax-deductible.',
    'donate.thankYouMessage': 'Thank you for considering supporting our mission. Together, we can create a more sustainable future.',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.system': 'सिस्टम',
    'nav.about': 'के बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.donate': 'दान करें',
    'nav.startSolving': 'शुरू करें',
    'nav.settings': 'सेटिंग्स',
    'nav.language': 'भाषा',
    
    // Homepage
    'home.badge': 'एआई-संचालित पुनः उपयोग विचार',
    'home.title': 'फिक्सिट मेंटर —',
    'home.titleHighlight': 'टूटी चीजों के लिए स्मार्ट आइडियाज़',
    'home.subtitle': 'अपनी टूटी या बेकार चीजों को फेंकने के बजाय उन्हें पुनः उपयोग करने के लिए रचनात्मक एआई-संचालित विचार प्राप्त करें।',
    'home.getStarted': 'आइडियाज़ पाएं',
    'home.learnMore': 'और जानें',
    'home.problemTitle': 'फेंकना क्यों?',
    'home.problemDesc': 'ज्यादातर लोग टूटी चीजों को बिना जाने फेंक देते हैं कि उन्हें रचनात्मक तरीके से पुनः उपयोग किया जा सकता है। हमारा एआई आपको उन्हें नया जीवन देने के स्मार्ट तरीके खोजने में मदद करता है।',
    'home.comparisonTitle': 'फिक्सिट मेंटर बनाम सामान्य एआई',
    'home.normalAI': 'सामान्य एआई',
    'home.fixitAI': 'फिक्सिट मेंटर',
    'home.diff1Normal': 'परफेक्ट प्रॉम्प्ट की जरूरत',
    'home.diff1Fixit': 'प्रॉम्प्ट की जरूरत नहीं',
    'home.diff2Normal': 'सामान्य सुझाव',
    'home.diff2Fixit': 'व्यक्तिगत परियोजना विचार',
    'home.diff3Normal': 'बजट विचार नहीं',
    'home.diff3Fixit': 'बजट-अनुकूल समाधान',
    'home.diff4Normal': 'जटिल सेटअप आवश्यक',
    'home.diff4Fixit': 'सरल 3-चरण प्रक्रिया',
    'home.diff5Normal': 'सीमित सामग्री मार्गदर्शन',
    'home.diff5Fixit': 'पूर्ण सामग्री और चरण',
    'home.howItWorksTitle': 'यह कैसे काम करता है',
    'home.howItWorksDesc': '3 सरल चरणों में स्मार्ट पुनः उपयोग विचार प्राप्त करें',
    'home.step1Title': 'पहचानें',
    'home.step1Desc': 'हमें अपनी टूटी चीज के बारे में बताएं',
    'home.step2Title': 'विश्लेषण करें',
    'home.step2Desc': 'हम पुनः उपयोग की संभावनाओं की जांच करते हैं',
    'home.step3Title': 'मूल्यांकन करें',
    'home.step3Desc': 'रचनात्मक परियोजना विचार प्राप्त करें',
    'home.exampleTitle': 'फिक्सिट मेंटर को क्या अलग बनाता है?',
    'home.exampleBadge': 'वास्तविक उदाहरण',
    'home.exampleQuestion': 'मेरे पास एक टूटा हुआ लैपटॉप है — मैं इसके साथ क्या कर सकता हूं?',
    'home.example1Title': '1. आइटम की पहचान करें',
    'home.example1Desc': 'टूटा हुआ लैपटॉप, गैर-कार्यात्मक स्क्रीन',
    'home.example2Title': '2. स्थिति का विश्लेषण करें',
    'home.example2Desc': 'काम कर रहे भाग: कीबोर्ड, हार्ड ड्राइव, मदरबोर्ड',
    'home.example3Title': '3. विकल्पों का मूल्यांकन करें',
    'home.example3Desc': 'डिजिटल फोटो फ्रेम, मीडिया सेंटर बनाएं या भागों को दान करें',
    'home.example4Title': '4. परियोजना विचार',
    'home.example4Desc': 'DIY होम सर्वर, रेट्रो गेमिंग कंसोल, कोडिंग सीखने का प्लेटफॉर्म',
    'home.tryIt': 'खुद आजमाएं',
    'home.footerDesc': 'टूटी चीजों को पुनः उपयोग करने के रचनात्मक विचार प्राप्त करने के लिए एक एआई-संचालित प्लेटफॉर्म।',
    'home.quickLinks': 'त्वरित लिंक',
    'home.contactTitle': 'संपर्क',
    'home.getInTouch': 'संपर्क में रहें',
    'home.copyright': '© 2025 फिक्सिट मेंटर। सर्वाधिकार सुरक्षित।',
    
    // System Page
    'system.title': 'स्मार्ट पुनः उपयोग विचार प्राप्त करें',
    'system.subtitle': 'हमें अपनी टूटी या बेकार चीज के बारे में बताएं और रचनात्मक एआई-संचालित सुझाव प्राप्त करें',
    'system.wasteItemLabel': 'टूटी/बेकार चीज',
    'system.wasteItemPlaceholder': 'अपनी टूटी या बेकार चीज का वर्णन करें... (जैसे, "टूटा लैपटॉप", "पुरानी प्लास्टिक बोतलें", "फटी जींस")',
    'system.budgetLabel': 'बजट (₹)',
    'system.budgetPlaceholder': 'आप कितना खर्च कर सकते हैं?',
    'system.otherInfoLabel': 'अतिरिक्त जानकारी (वैकल्पिक)',
    'system.otherInfoPlaceholder': 'कोई अन्य विवरण... (जैसे, "मेरे पास बुनियादी उपकरण हैं", "पर्यावरण के अनुकूल विचार पसंद करते हैं")',
    'system.generateButton': 'स्मार्ट पुनः उपयोग योजना बनाएं',
    'system.generating': 'विचार उत्पन्न हो रहे हैं...',
    'system.errorWasteItem': 'कृपया अपनी टूटी/बेकार चीज का वर्णन करें',
    'system.errorBudget': 'कृपया एक मान्य बजट दर्ज करें',
    
    // Response Page
    'response.backButton': 'सिस्टम पर वापस जाएं',
    'response.newPlan': 'नई योजना बनाएं',
    'response.noResponseTitle': 'अभी तक कोई प्रतिक्रिया उत्पन्न नहीं हुई',
    'response.noResponseDesc': 'प्रतिक्रिया खाली है। कृपया विभिन्न इनपुट के साथ पुनः प्रयास करें या अपने बैकएंड कॉन्फ़िगरेशन की जांच करें।',
    'response.errorDesc': 'आपकी योजना उत्पन्न करने में समस्या थी। यह एपीआई कॉन्फ़िगरेशन या कनेक्टिविटी समस्याओं के कारण हो सकता है।',
    'response.yourInputs': 'आपके इनपुट:',
    'response.wasteItem': 'टूटी चीज:',
    'response.budget': 'बजट:',
    'response.otherInfo': 'अन्य जानकारी:',
    'response.tryAgain': 'पुनः प्रयास करें',
    // Response Navigation
    'response.nav.overview': 'अवलोकन',
    'response.nav.idea': 'प्रोजेक्ट',
    'response.nav.materials': 'सामग्री',
    'response.nav.steps': 'चरण',
    'response.nav.budget': 'बजट',
    'response.nav.alternate': 'वैकल्पिक',
    'response.nav.safety': 'सुरक्षा',
    
    // Thank You Page
    'cashOnlyTitle': 'हम अभी केवल नकद स्वीकार करते हैं',
    'selectedAmount': 'चयनित राशि',
    'thankYouTitle': 'आपके समर्थन के लिए धन्यवाद!',
    'thankYouMessage1': 'आपका उदार दिल और योगदान करने की इच्छा हमारे लिए बहुत मायने रखती है। हर दान, चाहे कितना भी हो, हमें नवीन एआई समाधानों के माध्यम से अधिक टिकाऊ भविष्य बनाने के हमारे मिशन को जारी रखने में मदद करता है।',
    'thankYouMessage2': 'फिक्सिट मेंटर का समर्थन करके, आप अनगिनत लोगों को टूटी वस्तुओं का पुनः उपयोग करने, कचरा कम करने और पर्यावरण संरक्षण में योगदान करने के रचनात्मक तरीके खोजने में मदद कर रहे हैं।',
    'thankYouMessage3': 'आपके विचार और समर्थन के लिए हम गहराई से आभारी हैं। साथ मिलकर, हम एक हरित ग्रह की ओर वास्तविक अंतर ला सकते हैं।',
    'contactForDonation': 'अपना नकद दान पूरा करने के लिए, कृपया हमसे संपर्क करें:',
    'backToHome': 'होम पर वापस जाएं',
    
    // Dashboard Page
    'dashboard.title': 'समस्या',
    'dashboard.titleHighlight': 'डैशबोर्ड',
    'dashboard.subtitle': 'संरचित सोच प्रक्रिया शुरू करने के लिए एक श्रेणी चुनें या अपनी विशिष्ट समस्या खोजें',
    'dashboard.searchPlaceholder': 'अपनी समस्या खोजें... (जैसे, \'लैपटॉप चालू नहीं हो रहा\', \'अध्ययन कार्यक्रम चाहिए\')',
    'dashboard.categoriesTitle': 'सामान्य समस्या श्रेणियां',
    'dashboard.category1Title': 'इलेक्ट्रॉनिक कचरा',
    'dashboard.category1Desc': 'टूटे उपकरण, मरम्मत या बदलने के निर्णय',
    'dashboard.category2Title': 'स्कूल की समस्याएं',
    'dashboard.category2Desc': 'अध्ययन योजना, परियोजना प्रबंधन, समय अनुकूलन',
    'dashboard.category3Title': 'जलवायु / पर्यावरण',
    'dashboard.category3Desc': 'स्थिरता विकल्प, पर्यावरण के अनुकूल समाधान',
    'dashboard.category4Title': 'व्यक्तिगत मुद्दे',
    'dashboard.category4Desc': 'जीवन के निर्णय, रिश्ते, स्वास्थ्य विकल्प',
    'dashboard.category5Title': 'रचनात्मक निर्माण विचार',
    'dashboard.category5Desc': 'DIY परियोजनाएं, नवाचार, निर्माता समस्याएं',
    'dashboard.quickStartTitle': 'त्वरित शुरुआत उदाहरण',
    'dashboard.example1': 'मेरे लैपटॉप की स्क्रीन टूट गई है - मरम्मत करूं या बदलूं?',
    'dashboard.example2': 'मुझे 5 विषयों के लिए अध्ययन कार्यक्रम व्यवस्थित करना है',
    'dashboard.example3': 'बजट में कार्बन फुटप्रिंट कैसे कम करूं?',
    'dashboard.example4': 'मैं सौर-संचालित फोन चार्जर बनाना चाहता हूं',
    'dashboard.startSolving': 'समाधान शुरू करें',
    'dashboard.goToSystem': 'मुख्य सिस्टम पर जाएं',
    
    // About Page
    'about.title': 'के बारे में',
    'about.titleHighlight': 'फिक्सिट मेंटर',
    'about.subtitle': 'असंरचित और संरचित एआई के बीच अंतर को समझना',
    'about.whyNotJustAITitle': 'यह सिस्टम सिर्फ एआई क्यों नहीं है',
    'about.whyNotJustAIDesc': 'पारंपरिक एआई सिस्टम आपको तेज़ जवाब देते हैं, लेकिन उनमें वह संरचित सोच प्रक्रिया नहीं होती जो मनुष्य जटिल समस्याओं को हल करते समय स्वाभाविक रूप से उपयोग करते हैं। फिक्सिट मेंटर अलग है—यह एक फ्रेमवर्क है जो आपको समस्या-समाधान के प्रत्येक महत्वपूर्ण चरण के माध्यम से मार्गदर्शन करता है।',
    'about.unstructuredAI': 'असंरचित एआई',
    'about.structuredAI': 'संरचित एआई (फिक्सिट मेंटर)',
    'about.unstructured1': 'संदर्भ के बिना एकल उत्तर',
    'about.unstructured2': 'सोच के चरणों का कोई विभाजन नहीं',
    'about.unstructured3': 'आपकी बाधाओं पर विचार नहीं करता',
    'about.unstructured4': 'विकल्पों की कोई तुलना नहीं',
    'about.unstructured5': 'आपके संसाधनों के अनुकूल नहीं हो सकता',
    'about.structured1': 'निर्देशित 6-चरण कार्यप्रवाह',
    'about.structured2': 'प्रत्येक चरण का स्पष्ट विभाजन',
    'about.structured3': 'पहले से आपकी बाधाओं पर विचार करता है',
    'about.structured4': 'कई समाधान पथों की तुलना करता है',
    'about.structured5': 'आपके विशिष्ट संसाधनों के अनुकूल होता है',
    'about.whyPreferTitle': 'छात्र और नवप्रवर्तक संरचित सोच को क्यों पसंद करते हैं',
    'about.reason1Title': 'यादृच्छिक की बजाय संरचित',
    'about.reason1Desc': 'हमारा सिस्टम आपको व्यवस्थित रूप से सोचने के लिए मजबूर करता है, न कि पहले उत्तर पर प्रतिक्रिया करने के लिए।',
    'about.reason2Title': 'प्रक्रिया सीखें',
    'about.reason2Desc': 'आपको सिर्फ उत्तर नहीं मिलते—आप सीखते हैं कि भविष्य में समान समस्याओं को कैसे हल करें।',
    'about.reason3Title': 'मानव-जैसा तर्क',
    'about.reason3Desc': 'सफल समस्या-समाधानकर्ताओं की तरह सोचता है: पहचानें, विश्लेषण करें, मूल्यांकन करें, योजना बनाएं।',
    'about.reason4Title': 'बेहतर निर्णय',
    'about.reason4Desc': 'कई समाधानों और उनके प्रभावों की तुलना करके, आप सूचित विकल्प बनाते हैं।',
    'about.howItHelpsTitle': 'फिक्सिट मेंटर आपकी कैसे मदद करता है',
    'about.forStudents': 'छात्रों के लिए:',
    'about.forStudentsDesc': 'एक स्पष्ट, दोहराने योग्य विधि के साथ असाइनमेंट, परियोजनाओं और जीवन के निर्णयों का सामना करना सीखें।',
    'about.forInnovators': 'नवप्रवर्तकों के लिए:',
    'about.forInnovatorsDesc': 'अस्पष्ट विचारों को कार्रवाई योग्य योजनाओं में बदलें। चाहे आप उत्पाद बना रहे हों या परियोजना शुरू कर रहे हों।',
    'about.forEveryone': 'सभी के लिए:',
    'about.forEveryoneDesc': 'पूरी तस्वीर देखकर बेहतर निर्णय लें—संसाधन, बाधाएं, विकल्प और प्रभाव।',
    
    // Contact Page
    'contact.title': 'संपर्क',
    'contact.titleHighlight': 'करें',
    'contact.subtitle': 'फिक्सिट मेंटर के बारे में प्रश्न हैं? प्रतिक्रिया साझा करना चाहते हैं? हम आपसे सुनना चाहेंगे।',
    'contact.emailTitle': 'ईमेल करें',
    'contact.emailDesc': 'सामान्य पूछताछ और समर्थन के लिए',
    'contact.feedbackTitle': 'प्रतिक्रिया',
    'contact.feedbackDesc': 'हम उपयोगकर्ता प्रतिक्रिया के आधार पर फिक्सिट मेंटर को लगातार सुधार रहे हैं। अपने विचार साझा करें।',
    'contact.whyContactTitle': 'हमसे संपर्क क्यों करें?',
    'contact.whyContact1': 'बग या तकनीकी समस्या की रिपोर्ट करें',
    'contact.whyContact2': 'नई सुविधाओं या सुधारों का सुझाव दें',
    'contact.whyContact3': 'साझेदारी या सहयोग के अवसर',
    'contact.whyContact4': 'मीडिया पूछताछ',
    'contact.formTitle': 'हमें संदेश भेजें',
    'contact.nameLabel': 'आपका नाम',
    'contact.namePlaceholder': 'जॉन डो',
    'contact.emailLabel': 'ईमेल पता',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.messageLabel': 'संदेश',
    'contact.messagePlaceholder': 'हमें बताएं कि आप क्या सोच रहे हैं...',
    'contact.sendButton': 'संदेश भेजें',
    'contact.successMessage': 'संदेश भेजा गया! हम जल्द ही आपसे संपर्क करेंगे।',
    
    // Donate Page
    'donate.badge': 'हमारे मिशन का समर्थन करें',
    'donate.title': 'एक बनाने में मदद करें',
    'donate.titleHighlight': 'हरित भविष्य',
    'donate.subtitle': 'आपका योगदान हमें स्थायी जीवन और पर्यावरण संरक्षण के लिए बेहतर एआई उपकरण विकसित करने में मदद करता है।',
    'donate.impact1Title': 'कचरा कम करें',
    'donate.impact1Desc': 'हर दान हमें बेहतर रीसाइक्लिंग समाधान सुझाने के लिए हमारे एआई मॉडल को बेहतर बनाने में मदद करता है।',
    'donate.impact2Title': 'पर्यावरण बचाएं',
    'donate.impact2Desc': 'स्थायी तकनीक का समर्थन करें जो सभी के लिए पर्यावरण के अनुकूल विकल्पों को सुलभ बनाती है।',
    'donate.impact3Title': 'समुदायों को सशक्त बनाएं',
    'donate.impact3Desc': 'स्मार्ट रीसाइक्लिंग समाधानों तक मुफ्त पहुंच के साथ अधिक लोगों तक पहुंचने में हमारी मदद करें।',
    'donate.mainTitle': 'आज एक अंतर बनाएं',
    'donate.mainDesc': 'आपका उदार दान हमें कचरा कम करने और पर्यावरणीय स्थिरता के लिए नवीन एआई समाधान विकसित करने में मदद करेगा।',
    'donate.donateNow': 'अभी दान करें',
    'donate.securePayment': 'सुरक्षित भुगतान प्रसंस्करण। आपका योगदान कर-कटौती योग्य है।',
    'donate.thankYouMessage': 'हमारे मिशन का समर्थन करने पर विचार करने के लिए धन्यवाद। साथ मिलकर, हम एक अधिक स्थायी भविष्य बना सकते हैं।',
  },
  ur: {
    'nav.home': 'گھر',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.system': 'سسٹم',
    'nav.about': 'کے بارے میں',
    'nav.contact': 'رابطہ کریں',
    'nav.donate': 'عطیہ دیں',
    'nav.startSolving': 'شروع کریں',
    'nav.settings': 'ترتیبات',
    'nav.language': 'زبان',
    'home.badge': 'اے آئی سے چلنے والے دوبارہ استعمال کے خیالات',
    'home.title': 'فکسٹ منٹر —',
    'home.titleHighlight': 'ٹوٹی چیزوں کے لیے سمارٹ آئیڈیاز',
    'home.subtitle': 'اپنی ٹوٹی یا فضول چیزوں کو پھینکنے کے بجائے انہیں دوبارہ استعمال کرنے کے لیے تخلیقی اے آئی سے چلنے والے خیالات حاصل کریں۔',
    'home.getStarted': 'آئیڈیاز حاصل کریں',
    'home.learnMore': 'مزید جانیں',
    'response.nav.overview': 'جائزہ',
    'response.nav.idea': 'منصوبہ',
    'response.nav.materials': 'مواد',
    'response.nav.steps': 'اقدامات',
    'response.nav.budget': 'بجٹ',
    'response.nav.alternate': 'متبادل',
    'response.nav.safety': 'حفاظت',
    'dashboard.title': 'مسئلہ',
    'dashboard.titleHighlight': 'ڈیش بورڈ',
    'dashboard.subtitle': 'ساختہ سوچ کا عمل شروع کرنے کے لیے ایک زمرہ منتخب کریں یا اپنا مخصوص مسئلہ تلاش کریں',
    'about.title': 'کے بارے میں',
    'about.titleHighlight': 'فکسٹ منٹر',
    'contact.title': 'رابطہ',
    'contact.titleHighlight': 'کریں',
    'donate.title': 'مدد کریں بنانے میں',
    'donate.titleHighlight': 'سبز مستقبل',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.system': 'সিস্টেম',
    'nav.about': 'সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.donate': 'দান করুন',
    'nav.startSolving': 'শুরু করুন',
    'nav.settings': 'সেটিংস',
    'nav.language': 'ভাষা',
    'home.badge': 'এআই-চালিত পুনঃব্যবহার ধারণা',
    'home.title': 'ফিক্সিট মেন্টর —',
    'home.titleHighlight': 'ভাঙা জিনিসের জন্য স্মার্ট আইডিয়া',
    'home.subtitle': 'আপনার ভাঙা বা বর্জ্য জিনিসগুলি ফেলে না দিয়ে পুনরায় ব্যবহার করার জন্য সৃজনশীল এআই-চালিত ধারণা পান।',
    'home.getStarted': 'আইডিয়া পান',
    'home.learnMore': 'আরও জানুন',
    'response.nav.overview': 'সংক্ষিপ্ত',
    'response.nav.idea': 'প্রকল্প',
    'response.nav.materials': 'উপকরণ',
    'response.nav.steps': 'ধাপ',
    'response.nav.budget': 'বাজেট',
    'response.nav.alternate': 'বিকল্প',
    'response.nav.safety': 'নিরাপত্তা',
    'dashboard.title': 'সমস্যা',
    'dashboard.titleHighlight': 'ড্যাশবোর্ড',
    'dashboard.subtitle': 'কাঠামোগত চিন্তা প্রক্রিয়া শুরু করতে একটি বিভাগ নির্বাচন করুন বা আপনার নির্দিষ্ট সমস্যা অনুসন্ধান করুন',
    'about.title': 'সম্পর্কে',
    'about.titleHighlight': 'ফিক্সিট মেন্টর',
    'contact.title': 'যোগাযোগ',
    'contact.titleHighlight': 'করুন',
    'donate.title': 'সাহায্য করুন তৈরি করতে',
    'donate.titleHighlight': 'সবুজ ভবিষ্যৎ',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.system': 'சிஸ்டம்',
    'nav.about': 'பற்றி',
    'nav.contact': 'தொடர்பு',
    'nav.donate': 'நன்கொடை',
    'nav.startSolving': 'தொடங்கு',
    'nav.settings': 'அமைப்புகள்',
    'nav.language': 'மொழி',
    'home.badge': 'AI-இயங்கும் மறுபயன்பாட்டு யோசனைகள்',
    'home.title': 'ஃபிக்ஸிட் மெண்டர் —',
    'home.titleHighlight': 'உடைந்த பொருட்களுக்கான ஸ்மார்ட் ஐடியாக்கள்',
    'home.subtitle': 'உங்கள் உடைந்த அல்லது கழிவு பொருட்களை தூக்கி எறியாமல் மீண்டும் பயன்படுத்த ஆக்கப்பூர்வமான AI-இயங்கும் யோசனைகளைப் பெறுங்கள்.',
    'home.getStarted': 'யோசனைகளைப் பெறுங்கள்',
    'home.learnMore': 'மேலும் அறிக',
    'response.nav.overview': 'கண்ணோட்டம்',
    'response.nav.idea': 'திட்டம்',
    'response.nav.materials': 'பொருட்கள்',
    'response.nav.steps': 'படிகள்',
    'response.nav.budget': 'பட்ஜெட்',
    'response.nav.alternate': 'மாற்று',
    'response.nav.safety': 'பாதுகாப்பு',
    'dashboard.title': 'பிரச்சினை',
    'dashboard.titleHighlight': 'டாஷ்போர்டு',
    'dashboard.subtitle': 'கட்டமைக்கப்பட்ட சிந்தனை செயல்முறையைத் தொடங்க ஒரு வகையைத் தேர்வு செய்யவும் அல்லது உங்கள் குறிப்பிட்ட பிரச்சினையைத் தேடவும்',
    'about.title': 'பற்றி',
    'about.titleHighlight': 'ஃபிக்ஸிட் மெண்டர்',
    'contact.title': 'தொடர்பு',
    'contact.titleHighlight': 'கொள்ளுங்கள்',
    'donate.title': 'உருவாக்க உதவுங்கள்',
    'donate.titleHighlight': 'பசுமையான எதிர்காலம்',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.system': 'సిస్టమ్',
    'nav.about': 'గురించి',
    'nav.contact': 'సంప్రదించండి',
    'nav.donate': 'దానం చేయండి',
    'nav.startSolving': 'ప్రారంభించండి',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.language': 'భాష',
    'home.badge': 'AI-శక్తితో పునర్వినియోగ ఆలోచనలు',
    'home.title': 'ఫిక్సిట్ మెంటర్ —',
    'home.titleHighlight': 'విరిగిన వస్తువులకు స్మార్ట్ ఐడియాలు',
    'home.subtitle': 'మీ విరిగిన లేదా వ్యర్థ వస్తువులను విసిరేయకుండా తిరిగి ఉపయోగించడానికి సృజనాత్మక AI-శక్తితో ఆలోచనలను పొందండి.',
    'home.getStarted': 'ఆలోచనలు పొందండి',
    'home.learnMore': 'మరింత తెలుసుకోండి',
    'response.nav.overview': 'అవలోకనం',
    'response.nav.idea': 'ప్రాజెక్ట్',
    'response.nav.materials': 'సామగ్రి',
    'response.nav.steps': 'దశలు',
    'response.nav.budget': 'బడ్జెట్',
    'response.nav.alternate': 'ప్రత్యామ్నాయం',
    'response.nav.safety': 'భద్రత',
    'dashboard.title': 'సమస్య',
    'dashboard.titleHighlight': 'డాష్‌బోర్డ్',
    'dashboard.subtitle': 'నిర్మాణాత్మక ఆలోచన ప్రక్రియను ప్రారంభించడానికి ఒక వర్గాన్ని ఎంచుకోండి లేదా మీ నిర్దిష్ట సమస్యను శోధించండి',
    'about.title': 'గురించి',
    'about.titleHighlight': 'ఫిక్సిట్ మెంటర్',
    'contact.title': 'సంప్రదించండి',
    'contact.titleHighlight': '',
    'donate.title': 'నిర్మించడంలో సహాయం చేయండి',
    'donate.titleHighlight': 'పచ్చని భవిష్యత్తు',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.system': 'सिस्टीम',
    'nav.about': 'बद्दल',
    'nav.contact': 'संपर्क',
    'nav.donate': 'दान करा',
    'nav.startSolving': 'सुरू करा',
    'nav.settings': 'सेटिंग्ज',
    'nav.language': 'भाषा',
    'home.badge': 'AI-चालित पुन्हा वापर कल्पना',
    'home.title': 'फिक्सिट मेंटर —',
    'home.titleHighlight': 'तुटलेल्या वस्तूंसाठी स्मार्ट आयडिया',
    'home.subtitle': 'तुमच्या तुटलेल्या किंवा कचऱ्याच्या वस्तू फेकण्याऐवजी त्यांचा पुन्हा वापर करण्यासाठी सर्जनशील AI-चालित कल्पना मिळवा.',
    'home.getStarted': 'कल्पना मिळवा',
    'home.learnMore': 'अधिक जाणून घ्या',
    'response.nav.overview': 'सारांश',
    'response.nav.idea': 'प्रकल्प',
    'response.nav.materials': 'साहित्य',
    'response.nav.steps': 'टप्पे',
    'response.nav.budget': 'बजेट',
    'response.nav.alternate': 'पर्यायी',
    'response.nav.safety': 'सुरक्षा',
    'dashboard.title': 'समस्या',
    'dashboard.titleHighlight': 'डॅशबोर्ड',
    'dashboard.subtitle': 'संरचित विचार प्रक्रिया सुरू करण्यासाठी एक श्रेणी निवडा किंवा तुमची विशिष्ट समस्या शोधा',
    'about.title': 'बद्दल',
    'about.titleHighlight': 'फिक्सिट मेंटर',
    'contact.title': 'संपर्क',
    'contact.titleHighlight': 'करा',
    'donate.title': 'बनवण्यास मदत करा',
    'donate.titleHighlight': 'हरित भविष्य',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.system': 'સિસ્ટમ',
    'nav.about': 'વિશે',
    'nav.contact': 'સંપર્ક',
    'nav.donate': 'દાન કરો',
    'nav.startSolving': 'શરૂ કરો',
    'nav.settings': 'સેટિંગ્સ',
    'nav.language': 'ભાષા',
    'home.badge': 'AI-સંચાલિત પુનઃઉપયોગ વિચારો',
    'home.title': 'ફિક્સિટ મેંટર —',
    'home.titleHighlight': 'તૂટેલી વસ્તુઓ માટે સ્માર્ટ આઇડિયા',
    'home.subtitle': 'તમારી તૂટેલી અથવા કચરાની વસ્તુઓને ફેંકવાને બદલે તેનો ફરીથી ઉપયોગ કરવા માટે સર્જનાત્મક AI-સંચાલિત વિચારો મેળવો.',
    'home.getStarted': 'આઇડિયા મેળવો',
    'home.learnMore': 'વધુ જાણો',
    'response.nav.overview': 'સારાંશ',
    'response.nav.idea': 'પ્રોજેક્ટ',
    'response.nav.materials': 'સામગ્રી',
    'response.nav.steps': 'પગલાં',
    'response.nav.budget': 'બજેટ',
    'response.nav.alternate': 'વૈકલ્પિક',
    'response.nav.safety': 'સલામતી',
    'dashboard.title': 'સમસ્યા',
    'dashboard.titleHighlight': 'ડેશબોર્ડ',
    'dashboard.subtitle': 'સંરચિત વિચાર પ્રક્રિયા શરૂ કરવા માટે એક શ્રેણી પસંદ કરો અથવા તમારી ચોક્કસ સમસ્યા શોધો',
    'about.title': 'વિશે',
    'about.titleHighlight': 'ફિક્સિટ મેંટર',
    'contact.title': 'સંપર્ક',
    'contact.titleHighlight': 'કરો',
    'donate.title': 'બનાવવામાં મદદ કરો',
    'donate.titleHighlight': 'લીલું ભવિષ્ય',
  },
  kn: {
    'nav.home': 'ಹೋಮ್',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.system': 'ಸಿಸ್ಟಮ್',
    'nav.about': 'ಬಗ್ಗೆ',
    'nav.contact': 'ಸಂಪರ್ಕ',
    'nav.donate': 'ದಾನ ಮಾಡಿ',
    'nav.startSolving': 'ಪ್ರಾರಂಭಿಸಿ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.language': 'ಭಾಷೆ',
    'home.badge': 'AI-ಚಾಲಿತ ಮರುಬಳಕೆ ಆಲೋಚನೆಗಳು',
    'home.title': 'ಫಿಕ್ಸಿಟ್ ಮೆಂಟರ್ —',
    'home.titleHighlight': 'ಮುರಿದ ವಸ್ತುಗಳಿಗೆ ಸ್ಮಾರ್ಟ್ ಐಡಿಯಾಗಳು',
    'home.subtitle': 'ನಿಮ್ಮ ಮುರಿದ ಅಥವಾ ತ್ಯಾಜ್ಯ ವಸ್ತುಗಳನ್ನು ಎಸೆಯುವ ಬದಲು ಮರುಬಳಕೆ ಮಾಡಲು ಸೃಜನಶೀಲ AI-ಚಾಲಿತ ಆಲೋಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'home.getStarted': 'ಆಲೋಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ',
    'home.learnMore': 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
    'response.nav.overview': 'ಅವಲೋಕನ',
    'response.nav.idea': 'ಯೋಜನೆ',
    'response.nav.materials': 'ವಸ್ತುಗಳು',
    'response.nav.steps': 'ಹಂತಗಳು',
    'response.nav.budget': 'ಬಜೆಟ್',
    'response.nav.alternate': 'ಪರ್ಯಾಯ',
    'response.nav.safety': 'ಸುರಕ್ಷತೆ',
    'dashboard.title': 'ಸಮಸ್ಯೆ',
    'dashboard.titleHighlight': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'dashboard.subtitle': 'ರಚನಾತ್ಮಕ ಚಿಂತನೆ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಸಮಸ್ಯೆಯನ್ನು ಹುಡುಕಿ',
    'about.title': 'ಬಗ್ಗೆ',
    'about.titleHighlight': 'ಫಿಕ್ಸಿಟ್ ಮೆಂಟರ್',
    'contact.title': 'ಸಂಪರ್ಕಿಸಿ',
    'contact.titleHighlight': '',
    'donate.title': 'ನಿರ್ಮಿಸಲು ಸಹಾಯ ಮಾಡಿ',
    'donate.titleHighlight': 'ಹಸಿರು ಭವಿಷ್ಯ',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.dashboard': 'ഡാഷ്ബോർഡ്',
    'nav.system': 'സിസ്റ്റം',
    'nav.about': 'കുറിച്ച്',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.donate': 'സംഭാവന ചെയ്യുക',
    'nav.startSolving': 'ആരംഭിക്കുക',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.language': 'ഭാഷ',
    'home.badge': 'AI-പവർഡ് പുനരുപയോഗ ആശയങ്ങൾ',
    'home.title': 'ഫിക്സിറ്റ് മെന്റർ —',
    'home.titleHighlight': 'തകർന്ന വസ്തുക്കൾക്കുള്ള സ്മാർട്ട് ആശയങ്ങൾ',
    'home.subtitle': 'നിങ്ങളുടെ തകർന്ന അല്ലെങ്കിൽ മാലിന്യ വസ്തുക്കൾ വലിച്ചെറിയുന്നതിനുപകരം പുനരുപയോഗിക്കാൻ സൃഷ്ടിപരമായ AI-പവർഡ് ആശയങ്ങൾ നേടുക.',
    'home.getStarted': 'ആശയങ്ങൾ നേടുക',
    'home.learnMore': 'കൂടുതൽ അറിയുക',
    'response.nav.overview': 'അവലോകനം',
    'response.nav.idea': 'പ്രോജക്ട്',
    'response.nav.materials': 'വസ്തുക്കൾ',
    'response.nav.steps': 'ഘട്ടങ്ങൾ',
    'response.nav.budget': 'ബജറ്റ്',
    'response.nav.alternate': 'ബദൽ',
    'response.nav.safety': 'സുരക്ഷ',
    'dashboard.title': 'പ്രശ്നം',
    'dashboard.titleHighlight': 'ഡാഷ്ബോർഡ്',
    'dashboard.subtitle': 'ഘടനാപരമായ ചിന്താ പ്രക്രിയ ആരംഭിക്കാൻ ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ നിങ്ങളുടെ പ്രത്യേക പ്രശ്നം തിരയുക',
    'about.title': 'കുറിച്ച്',
    'about.titleHighlight': 'ഫിക്സിറ്റ് മെന്റർ',
    'contact.title': 'ബന്ധപ്പെടുക',
    'contact.titleHighlight': '',
    'donate.title': 'നിർമ്മിക്കാൻ സഹായിക്കൂ',
    'donate.titleHighlight': 'പച്ച ഭാവി',
  },
  pa: {
    'nav.home': 'ਹੋਮ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.system': 'ਸਿਸਟਮ',
    'nav.about': 'ਬਾਰੇ',
    'nav.contact': 'ਸੰਪਰਕ ਕਰੋ',
    'nav.donate': 'ਦਾਨ ਕਰੋ',
    'nav.startSolving': 'ਸ਼ੁਰੂ ਕਰੋ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'nav.language': 'ਭਾਸ਼ਾ',
    'home.badge': 'AI-ਸੰਚਾਲਿਤ ਮੁੜ ਵਰਤੋਂ ਵਿਚਾਰ',
    'home.title': 'ਫਿਕਸਿਟ ਮੈਂਟਰ —',
    'home.titleHighlight': 'ਟੁੱਟੀਆਂ ਚੀਜ਼ਾਂ ਲਈ ਸਮਾਰਟ ਆਈਡੀਆ',
    'home.subtitle': 'ਆਪਣੀਆਂ ਟੁੱਟੀਆਂ ਜਾਂ ਕੂੜੇ ਦੀਆਂ ਚੀਜ਼ਾਂ ਨੂੰ ਸੁੱਟਣ ਦੀ ਬਜਾਏ ਮੁੜ ਵਰਤੋਂ ਕਰਨ ਲਈ ਰਚਨਾਤਮਕ AI-ਸੰਚਾਲਿਤ ਵਿਚਾਰ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'home.getStarted': 'ਆਈਡੀਆ ਪ੍ਰਾਪਤ ਕਰੋ',
    'home.learnMore': 'ਹੋਰ ਜਾਣੋ',
    'response.nav.overview': 'ਸੰਖੇਪ',
    'response.nav.idea': 'ਪ੍ਰੋਜੈਕਟ',
    'response.nav.materials': 'ਸਮੱਗਰੀ',
    'response.nav.steps': 'ਕਦਮ',
    'response.nav.budget': 'ਬਜਟ',
    'response.nav.alternate': 'ਵਿਕਲਪਕ',
    'response.nav.safety': 'ਸੁਰੱਖਿਆ',
    'dashboard.title': 'ਸਮੱਸਿਆ',
    'dashboard.titleHighlight': 'ਡੈਸ਼ਬੋਰਡ',
    'dashboard.subtitle': 'ਢਾਂਚਾਗਤ ਸੋਚ ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਕ ਸ਼੍ਰੇਣੀ ਚੁਣੋ ਜਾਂ ਆਪਣੀ ਖਾਸ ਸਮੱਸਿਆ ਲੱਭੋ',
    'about.title': 'ਬਾਰੇ',
    'about.titleHighlight': 'ਫਿਕਸਿਟ ਮੈਂਟਰ',
    'contact.title': 'ਸੰਪਰਕ',
    'contact.titleHighlight': 'ਕਰੋ',
    'donate.title': 'ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰੋ',
    'donate.titleHighlight': 'ਹਰਾ ਭਵਿੱਖ',
  },
  or: {
    'nav.home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    'nav.dashboard': 'ଡାସବୋର୍ଡ',
    'nav.system': 'ସିଷ୍ଟମ',
    'nav.about': 'ବିଷୟରେ',
    'nav.contact': 'ଯୋଗାଯୋଗ',
    'nav.donate': 'ଦାନ କରନ୍ତୁ',
    'nav.startSolving': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'nav.settings': 'ସେଟିଂସ',
    'nav.language': 'ଭାଷା',
    'home.badge': 'AI-ଚାଳିତ ପୁନଃବ୍ୟବହାର ଧାରଣା',
    'home.title': 'ଫିକ୍ସିଟ ମେଣ୍ଟର —',
    'home.titleHighlight': 'ଭଙ୍ଗା ଜିନିଷ ପାଇଁ ସ୍ମାର୍ଟ ଆଇଡିଆ',
    'home.subtitle': 'ଆପଣଙ୍କର ଭଙ୍ଗା କିମ୍ବା ବର୍ଜ୍ୟ ଜିନିଷଗୁଡ଼ିକୁ ଫୋପାଡି ନ ଦେଇ ପୁନଃବ୍ୟବହାର କରିବା ପାଇଁ ସୃଜନଶୀଳ AI-ଚାଳିତ ଧାରଣା ପାଆନ୍ତୁ।',
    'home.getStarted': 'ଆଇଡିଆ ପାଆନ୍ତୁ',
    'home.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'response.nav.overview': 'ସାରାଂଶ',
    'response.nav.idea': 'ପ୍ରୋଜେକ୍ଟ',
    'response.nav.materials': 'ସାମଗ୍ରୀ',
    'response.nav.steps': 'ପଦକ୍ଷେପ',
    'response.nav.budget': 'ବଜେଟ',
    'response.nav.alternate': 'ବିକଳ୍ପ',
    'response.nav.safety': 'ସୁରକ୍ଷା',
    'dashboard.title': 'ସମସ୍ୟା',
    'dashboard.titleHighlight': 'ଡାସବୋର୍ଡ',
    'dashboard.subtitle': 'ସଂରଚନାତ୍ମକ ଚିନ୍ତା ପ୍ରକ୍ରିୟା ଆରମ୍ଭ କରିବାକୁ ଏକ ଶ୍ରେଣୀ ବାଛନ୍ତୁ କିମ୍ବା ଆପଣଙ୍କର ନିର୍ଦ୍ଦିଷ୍ଟ ସମସ୍ୟା ଖୋଜନ୍ତୁ',
    'about.title': 'ବିଷୟରେ',
    'about.titleHighlight': 'ଫିକ୍ସିଟ ମେଣ୍ଟର',
    'contact.title': 'ଯୋଗାଯୋଗ',
    'contact.titleHighlight': 'କରନ୍ତୁ',
    'donate.title': 'ନିର୍ମାଣ କରିବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ',
    'donate.titleHighlight': 'ସବୁଜ ଭବିଷ୍ୟତ',
  },
  as: {
    'nav.home': 'মূল পৃষ্ঠা',
    'nav.dashboard': 'ডেশবৰ্ড',
    'nav.system': 'চিষ্টেম',
    'nav.about': 'বিষয়ে',
    'nav.contact': 'যোগাযোগ',
    'nav.donate': 'দান কৰক',
    'nav.startSolving': 'আৰম্ভ কৰক',
    'nav.settings': 'ছেটিংছ',
    'nav.language': 'ভাষা',
    'home.badge': 'AI-চালিত পুনৰ ব্যৱহাৰ ধাৰণা',
    'home.title': 'ফিক্সিট মেণ্টৰ —',
    'home.titleHighlight': 'ভঙা বস্তুৰ বাবে স্মাৰ্ট আইডিয়া',
    'home.subtitle': 'আপোনাৰ ভঙা বা আৱৰ্জনা বস্তু পেলাই নিদি পুনৰ ব্যৱহাৰ কৰিবলৈ সৃজনশীল AI-চালিত ধাৰণা লাভ কৰক।',
    'home.getStarted': 'আইডিয়া লাভ কৰক',
    'home.learnMore': 'অধিক জানক',
    'response.nav.overview': 'সাৰাংশ',
    'response.nav.idea': 'প্ৰকল্প',
    'response.nav.materials': 'সামগ্ৰী',
    'response.nav.steps': 'পদক্ষেপ',
    'response.nav.budget': 'বাজেট',
    'response.nav.alternate': 'বিকল্প',
    'response.nav.safety': 'সুৰক্ষা',
    'dashboard.title': 'সমস্যা',
    'dashboard.titleHighlight': 'ডেশবৰ্ড',
    'dashboard.subtitle': 'সংগঠিত চিন্তা প্ৰক্ৰিয়া আৰম্ভ কৰিবলৈ এটা শ্ৰেণী বাছক বা আপোনাৰ নিৰ্দিষ্ট সমস্যা বিচাৰক',
    'about.title': 'বিষয়ে',
    'about.titleHighlight': 'ফিক্সিট মেণ্টৰ',
    'contact.title': 'যোগাযোগ',
    'contact.titleHighlight': 'কৰক',
    'donate.title': 'নিৰ্মাণত সহায় কৰক',
    'donate.titleHighlight': 'সেউজীয়া ভৱিষ্যত',
  },
};
